services:
  reverse-proxy:
    build: ReverseProxy/.
    container_name: reverse-proxy
    ports:
      - target: 80
        published: 80
      - target: 443
        published: 443
    networks:
      - frontend-tier
      - backend-tier
      - reverse-proxy-tier
    volumes:
      - reverse-proxy-cache:/var/cache/nginx

  frontend:
    build: Frontend/.
    networks:
      - frontend-tier

  backend:
    build: Backend/.
    container_name: backend
    env_file:
      - Backend/.env
    environment:
      DB_URL: mongodb://mongo:27017/BackendProject
    networks:
      - frontend-tier
      - backend-tier

  mongo:
    image: mongo:7
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - backend-tier

networks:
  frontend-tier:
    internal: true
  backend-tier:
    internal: true
  reverse-proxy-tier:


volumes:
  mongo_data:
  reverse-proxy-cache: