version: "3.9"

services:
  backend:
    build: Backend/.
    container_name: backend
    ports:
      - target: 3333
        published: 3333


    env_file:
      - Backend/.env
    environment:
      DB_URL: mongodb://mongo:27017/BackendProject
    networks:
      express-url-shortener:
      backend-internal-net:

  mongo:
    image: mongo:7
    container_name: mongo
    volumes:
      - type: volume
        source: mongo_data
        target: /data/db
    networks:
      backend-internal-net:

  frontend:
    build: Frontend/.
    ports:
      - target: 80
        published: 80
    networks:
      express-url-shortener:

networks:
  express-url-shortener:

  backend-internal-net:
    internal: true


volumes:
  mongo_data:
    name: mongo_data