services:
  reverse-proxy:
    image: ghcr.io/mostafaosmanfathi/express-url-shortener-reverse-proxy:v1.1
    container_name: reverse-proxy
    ports:
      - target: 80
        published: 80
      - target: 443
        published: 443
    networks:
      - frontend-tier
      - backend-tier
      - reverse-proxy-tier
    volumes:
      - reverse-proxy-cache:/var/cache/nginx

  frontend:
    image: ghcr.io/mostafaosmanfathi/express-url-shortener-frontend:v1.1
    networks:
      - frontend-tier

  backend:
    image: ghcr.io/mostafaosmanfathi/express-url-shortener-backend:v1.1
    container_name: backend
    environment:
      DB_URL: mongodb://mongo:27017/BackendProject
      JWT_SECRET: SECRET_KEY
      TOKEN_EXPIRY: 10m
      PORT: 3333
      HOST_NAME: 0.0.0.0
    networks:
      - frontend-tier
      - backend-tier

  mongo:
    image: mongo:7
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - backend-tier

networks:
  frontend-tier:
      internal: true
  backend-tier:
    internal: true
  reverse-proxy-tier:


volumes:
  mongo_data:
  reverse-proxy-cache: